/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JLua_JLua */

#ifndef _Included_JLua_JLua
#define _Included_JLua_JLua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JLua_JLua
 * Method:    v_invoke
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_v_1invoke
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     JLua_JLua
 * Method:    s_invoke
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLua_JLua_s_1invoke
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     JLua_JLua
 * Method:    i_invoke
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JLua_JLua_i_1invoke
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
