/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JLua_JLua */

#ifndef _Included_JLua_JLua
#define _Included_JLua_JLua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JLua_JLua
 * Method:    initLua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JLua_JLua_initLua
  (JNIEnv *, jobject);

/*
 * Class:     JLua_JLua
 * Method:    loadScript
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_loadScript
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JLua_JLua
 * Method:    callFunction
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLua_JLua_callFunction
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     JLua_JLua
 * Method:    closeLua
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_closeLua
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
