/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JLua_JLua */

#ifndef _Included_JLua_JLua
#define _Included_JLua_JLua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JLua_JLua
 * Method:    newstate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JLua_JLua_newstate
  (JNIEnv *, jobject);

/*
 * Class:     JLua_JLua
 * Method:    openlibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_openlibs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JLua_JLua
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JLua_JLua
 * Method:    pushstring
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_pushstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JLua_JLua
 * Method:    tostring
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLua_JLua_tostring
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JLua_JLua
 * Method:    pushinteger
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_pushinteger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JLua_JLua
 * Method:    getglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JLua_JLua_getglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JLua_JLua
 * Method:    gettop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_JLua_JLua_gettop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JLua_JLua
 * Method:    pcall
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_JLua_JLua_pcall
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     JLua_JLua
 * Method:    dofile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JLua_JLua_dofile
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
